int f11 =1;
int f12 =2;
int f13 =3;
int f21 =4;
int f22 =5;
int f23 =6;
int f31 =7;
int f32 =8;
int f33 =9;
int f41 =10;
int f42 =11;
int f43 =12;
void setup(){
  pinMode (f11,OUTPUT);
  pinMode (f12,OUTPUT);
  pinMode (f13,OUTPUT);
  pinMode (f21,OUTPUT);
  pinMode (f22,OUTPUT);
  pinMode (f23,OUTPUT);
  pinMode (f31,OUTPUT);
  pinMode (f32,OUTPUT);
  pinMode (f33,OUTPUT);
  pinMode (f41,OUTPUT);
  pinMode (f42,OUTPUT);
  pinMode (f43,OUTPUT);
} 
void loop (){
  
  digitalWrite (f11,HIGH);
  digitalWrite (f12,LOW);
  digitalWrite (f13,LOW);
  digitalWrite (f21,LOW);
  digitalWrite (f22,LOW);
  digitalWrite (f23,HIGH);
  digitalWrite (f31,HIGH);
  digitalWrite (f32,LOW);
  digitalWrite (f33,LOW);
  digitalWrite (f41,LOW);
  digitalWrite (f42,LOW);
  digitalWrite (f43,HIGH);
  delay (500);
  digitalWrite (f11,LOW);
  digitalWrite (f12,HIGH);
  digitalWrite (f13,LOW);
  digitalWrite (f21,LOW);
  digitalWrite (f22,HIGH);
  digitalWrite (f23,LOW);
  digitalWrite (f31,LOW);
  digitalWrite (f32,HIGH);
  digitalWrite (f33,LOW);
  digitalWrite (f41,LOW);
  digitalWrite (f42,HIGH);
  digitalWrite (f43,LOW);
  delay (500);
  digitalWrite (f11,LOW);
  digitalWrite (f12,LOW);
  digitalWrite (f13,HIGH);
  digitalWrite (f21,HIGH);
  digitalWrite (f22,LOW);
  digitalWrite (f23,LOW);
  digitalWrite (f31,LOW);
  digitalWrite (f32,LOW);
  digitalWrite (f33,HIGH);
  digitalWrite (f41,HIGH);
  digitalWrite (f42,LOW);
  digitalWrite (f43,LOW);
  delay (500);
  digitalWrite (f11,LOW);
  digitalWrite (f12,HIGH);
  digitalWrite (f13,LOW);
  digitalWrite (f21,LOW);
  digitalWrite (f22,HIGH);
  digitalWrite (f23,LOW);
  digitalWrite (f31,LOW);
  digitalWrite (f32,HIGH);
  digitalWrite (f33,LOW);
  digitalWrite (f41,LOW);
  digitalWrite (f42,HIGH);
  digitalWrite (f43,LOW);
  delay (500);
}
  
